using Microsoft.CodeAnalysis;

namespace Enhanced.AssemblyMarker.SourceGenerator;

/// <summary>
///     A source generator that creates C# assembly marker classes.
/// </summary>
[Generator]
public class AssemblyMarkerSourceGenerator : ISourceGenerator
{
    /// <inheritdoc />
    public void Initialize(GeneratorInitializationContext context)
    {
    }

    /// <inheritdoc />
    public void Execute(GeneratorExecutionContext context)
    {
        var assemblyName = context.Compilation.Assembly.Identity.Name;
        var className = assemblyName
                        .Replace('.', '_')
                        .Replace('-', '_');

        var assemblyMarkerSource = $@"// <auto-generated/>

namespace Projects
{{
    public static partial class {className}
    {{
        public interface Ref;

        public const global::System.String AssemblyName = ""{assemblyName}"";
        public static global::System.Reflection.Assembly Assembly => This.Assembly;
    }}
}}
";

        context.AddSource("AssemblyMarker.g.cs", assemblyMarkerSource);

        var thisAssemblySource = @"// <auto-generated/>

internal static class This {
    public static global::System.Reflection.Assembly Assembly => typeof(This).Assembly;
}
";
        context.AddSource("This.Assembly.g.cs", thisAssemblySource);
    }
}
